/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.alg3.minhaconsulta.view;


/**
 *
 * @author André Micael Sampaio Pinto <andre at alg3.org>
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        
      
       
        initComponents();
        
         addActionListeners(); // Chama o método que adiciona os ActionListeners
    }

    private void addActionListeners() {
        // Adiciona ActionListener ao item "Novo Paciente"
        
      
       CadastroPaciente.addActionListener((java.awt.event.ActionEvent evt) -> {
           // Código para abrir a tela de cadastro do paciente
           TelaCadastroCliente telaCadastro = new TelaCadastroCliente();
            telaCadastro.setVisible(true);
            telaCadastro.toFront();
        });

        NovoMedico.addActionListener((java.awt.event.ActionEvent evt) -> {
            // Código para abrir a tela de cadastro do médico
            TelaCadastroMedico telaCadastro = new TelaCadastroMedico();
            telaCadastro.setVisible(true);
            telaCadastro.toFront();
        });

      
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImgPrincipal = new javax.swing.JPanel();
        ImgPaginaInicial = new javax.swing.JLabel();
        MenuPrincipal = new javax.swing.JMenuBar();
        MenuCadastros = new javax.swing.JMenu();
        VerPacientes = new javax.swing.JMenuItem();
        VerConvenios = new javax.swing.JMenuItem();
        VerEspecialidades = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        CadastroPaciente = new javax.swing.JMenuItem();
        NovoMedico = new javax.swing.JMenuItem();
        MenuConsultas = new javax.swing.JMenu();
        NovaConsulta = new javax.swing.JMenuItem();
        ConsultasHoje = new javax.swing.JMenuItem();
        VerTodasConsultas = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        BuscarConsultas = new javax.swing.JMenu();
        PorDataConsulta = new javax.swing.JMenuItem();
        PorStatusConsulta = new javax.swing.JMenuItem();
        MenuBuscarMedico = new javax.swing.JMenu();
        PorEspecialidade = new javax.swing.JMenuItem();
        PorNome = new javax.swing.JMenuItem();
        PorCRM = new javax.swing.JMenuItem();
        FecharMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Minha Consulta");
        setResizable(false);

        ImgPrincipal.setBackground(new java.awt.Color(153, 153, 153));
        ImgPrincipal.setForeground(new java.awt.Color(255, 153, 153));
        ImgPrincipal.setToolTipText("");

        ImgPaginaInicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ImgPrincipal.png"))); // NOI18N

        javax.swing.GroupLayout ImgPrincipalLayout = new javax.swing.GroupLayout(ImgPrincipal);
        ImgPrincipal.setLayout(ImgPrincipalLayout);
        ImgPrincipalLayout.setHorizontalGroup(
            ImgPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ImgPaginaInicial, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        ImgPrincipalLayout.setVerticalGroup(
            ImgPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ImgPaginaInicial, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        MenuCadastros.setText("Cadastros");

        VerPacientes.setText("Ver Pacientes");
        MenuCadastros.add(VerPacientes);

        VerConvenios.setText("Ver Convênios");
        MenuCadastros.add(VerConvenios);

        VerEspecialidades.setText("Ver Especialidades");
        MenuCadastros.add(VerEspecialidades);
        MenuCadastros.add(jSeparator1);

        CadastroPaciente.setText("Novo Paciente");
        MenuCadastros.add(CadastroPaciente);

        NovoMedico.setText("Novo Médico");
        MenuCadastros.add(NovoMedico);

        MenuPrincipal.add(MenuCadastros);

        MenuConsultas.setText("Consultas");

        NovaConsulta.setText("Nova Consulta");
        MenuConsultas.add(NovaConsulta);

        ConsultasHoje.setText("Consultas de Hoje");
        MenuConsultas.add(ConsultasHoje);

        VerTodasConsultas.setText("Todas as Consultas");
        VerTodasConsultas.setToolTipText("");
        MenuConsultas.add(VerTodasConsultas);
        MenuConsultas.add(jSeparator2);

        BuscarConsultas.setText("Buscar Consultas");

        PorDataConsulta.setText("Por Data");
        BuscarConsultas.add(PorDataConsulta);

        PorStatusConsulta.setText("Por Status");
        BuscarConsultas.add(PorStatusConsulta);

        MenuConsultas.add(BuscarConsultas);

        MenuPrincipal.add(MenuConsultas);

        MenuBuscarMedico.setText("Buscar Medico");

        PorEspecialidade.setText("Por Especialidade");
        MenuBuscarMedico.add(PorEspecialidade);

        PorNome.setText("Por Nome");
        MenuBuscarMedico.add(PorNome);

        PorCRM.setText("Por CRM");
        MenuBuscarMedico.add(PorCRM);

        MenuPrincipal.add(MenuBuscarMedico);

        FecharMenu.setText("Fechar");
        MenuPrincipal.add(FecharMenu);

        setJMenuBar(MenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ImgPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ImgPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu BuscarConsultas;
    private javax.swing.JMenuItem CadastroPaciente;
    private javax.swing.JMenuItem ConsultasHoje;
    private javax.swing.JMenu FecharMenu;
    private javax.swing.JLabel ImgPaginaInicial;
    private javax.swing.JPanel ImgPrincipal;
    private javax.swing.JMenu MenuBuscarMedico;
    private javax.swing.JMenu MenuCadastros;
    private javax.swing.JMenu MenuConsultas;
    private javax.swing.JMenuBar MenuPrincipal;
    private javax.swing.JMenuItem NovaConsulta;
    private javax.swing.JMenuItem NovoMedico;
    private javax.swing.JMenuItem PorCRM;
    private javax.swing.JMenuItem PorDataConsulta;
    private javax.swing.JMenuItem PorEspecialidade;
    private javax.swing.JMenuItem PorNome;
    private javax.swing.JMenuItem PorStatusConsulta;
    private javax.swing.JMenuItem VerConvenios;
    private javax.swing.JMenuItem VerEspecialidades;
    private javax.swing.JMenuItem VerPacientes;
    private javax.swing.JMenuItem VerTodasConsultas;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
